// SHOPPING CART
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const INCREMENT_QUANTITY_CART_ITEM = "INCREMENT_QUANTITY_CART_ITEM";
export const DECREMENT_QUANTITY_CART_ITEM = "DECREMENT_QUANTITY_CART_ITEM";
export const RESET_CART = "RESET_CART";