export const TYPES = {
      ADD_CART_ITEM: "ADD_CART_ITEM",
      DELETE_CART_ITEM: "DELETE_CART_ITEM",
      INCREMENT_QUANTITY_CART_ITEM: "INCREMENT_QUANTITY_CART_ITEM",
      DECREMENT_QUANTITY_CART_ITEM: "DECREMENT_QUANTITY_CART_ITEM",
      RESET_CART: "RESET_CART"
}